import { Task } from "@/@types/tasks"
import { Twitter, MessageCircle, Repeat, Heart, Share2, Users, Sparkles, Shield, Award } from "lucide-react"

export const initialTasks: Task[] = [
  {
    id: "follow-twitter",
    title: "Follow CromaChain on X (Twitter)",
    description: "Follow our official X account to stay updated with the latest news and announcements.",
    category: "social",
    platform: "Twitter",
    reward: 50,
    difficulty: "Easy",
    timeEstimate: "1 min",
    status: "not-started",
    locked: false,
    iconName: "Twitter",
    action: "Follow",
    link: "https://x.com/cromachain",
    requirements: ["Must follow @cromachain", "Account must be public"],
  },
  {
    id: "retweet-announcement",
    title: "Retweet Airdrop Announcement",
    description: "Retweet our pinned airdrop announcement to spread the word.",
    category: "social",
    platform: "Twitter",
    reward: 75,
    difficulty: "Easy",
    timeEstimate: "1 min",
    status: "not-started",
    locked: false,
    iconName: "Repeat",
    action: "Retweet",
    link: "https://x.com/cromachain",
    requirements: ["Must retweet the pinned post", "Keep the retweet for 7 days"],
  },
  {
    id: "join-discord",
    title: "Join Discord Community",
    description: "Join our Discord server and introduce yourself in the #introductions channel.",
    category: "community",
    platform: "Discord",
    reward: 100,
    difficulty: "Easy",
    timeEstimate: "3 min",
    status: "not-started",
    locked: false,
    iconName: "MessageCircle",
    action: "Join",
    link: "https://discord.gg/SWj8TWfu9k",
    requirements: ["Join the Discord server", "Post introduction in #introductions"],
  },
  {
    id: "join-telegram",
    title: "Join Telegram Channel",
    description: "Join our Telegram channel for real-time updates and community discussions.",
    category: "community",
    platform: "Telegram",
    reward: 75,
    difficulty: "Easy",
    timeEstimate: "2 min",
    status: "not-started",
    locked: false,
    iconName: "MessageCircle",
    action: "Join",
    link: "https://t.me/Cromaartofficial",
    requirements: ["Join the Telegram channel", "Stay active for 7 days"],
  },
  {
    id: "like-posts",
    title: "Like 5 Recent Posts",
    description: "Show your support by liking our 5 most recent Twitter posts.",
    category: "social",
    platform: "Twitter",
    reward: 25,
    difficulty: "Easy",
    timeEstimate: "2 min",
    status: "not-started",
    locked: false,
    iconName: "Heart",
    action: "Like",
    requirements: ["Like 5 recent posts", "Must be genuine engagement"],
  },
  {
    id: "share-story",
    title: "Share on Instagram Story",
    description: "Share our airdrop announcement on your Instagram story and tag us.",
    category: "social",
    platform: "Instagram",
    reward: 100,
    difficulty: "Medium",
    timeEstimate: "5 min",
    status: "not-started",
    locked: false,
    iconName: "Share2",
    action: "Share",
    requirements: ["Share to Instagram story", "Tag @cromachain", "Keep story for 24h"],
  },
  {
    id: "invite-friends",
    title: "Invite 3 Friends",
    description: "Invite 3 friends to join the airdrop using your referral code.",
    category: "community",
    platform: "Referral",
    reward: 200,
    difficulty: "Medium",
    timeEstimate: "10 min",
    status: "not-started",
    locked: false,
    iconName: "Users",
    action: "Invite",
    requirements: ["Invite 3 unique users", "Friends must complete registration"],
  },
  {
    id: "create-content",
    title: "Create Content About CromaChain",
    description: "Create original content (video, blog post, or thread) about CromaChain and share it.",
    category: "bonus",
    platform: "Any",
    reward: 500,
    difficulty: "Hard",
    timeEstimate: "30 min",
    status: "not-started",
    locked: false,
    iconName: "Sparkles",
    action: "Create",
    requirements: ["Original content only", "Minimum 100 words/30 seconds", "Must mention key features"],
  },
  {
    id: "wallet-connect",
    title: "Connect Wallet (Coming Soon)",
    description: "Connect your wallet to verify ownership and prepare for token distribution.",
    category: "onchain",
    platform: "Blockchain",
    reward: 150,
    difficulty: "Easy",
    timeEstimate: "2 min",
    status: "not-started",
    locked: true,
    iconName: "Shield",
    action: "Connect",
    requirements: ["Valid Ethereum wallet", "Minimum 0.001 ETH for gas"],
  },
  {
    id: "nft-holder",
    title: "Hold CromaArt NFT (Bonus)",
    description: "Hold any CromaArt NFT in your wallet to earn bonus rewards.",
    category: "bonus",
    platform: "OpenSea",
    reward: 1000,
    difficulty: "Hard",
    timeEstimate: "Variable",
    status: "not-started",
    locked: false,
    iconName: "Award",
    action: "Hold",
    link: "https://opensea.io/collection/croma-art",
    requirements: ["Own any CromaArt NFT", "Hold for minimum 30 days"],
  },
]

// Helper function to get icon component by name
export const getTaskIcon = (iconName: string) => {
  const iconMap = {
    Twitter,
    MessageCircle,
    Repeat,
    Heart,
    Share2,
    Users,
    Sparkles,
    Shield,
    Award,
  }

  return iconMap[iconName as keyof typeof iconMap] || MessageCircle
}
